---
title: "Procrastination and Dementia"
format: 
  gfm: 
    wrap: preserve
    toc: true
  typst:
    toc: true
    toc-title: " "
    author:
    - name: Audrey L. Comstock
      affiliation: Arizona State University
      orcid: 0000-0003-1772-5350
      url: https://audreylcomstock.weebly.com/
      email: audrey.comstock@asu.edu
    - name: Andrew Heiss
      affiliation: Georgia State University
      orcid: 0000-0002-3948-3914
      url: https://www.andrewheiss.com
      email: aheiss@gsu.edu
    - name: Suparna Chaudhry
      affiliation: Lewis and Clark College
      orcid: 0000-0003-3506-7590
      url: https://www.suparnachaudhry.com/
      email: schaudhry@lclark.edu
---

<!-- README.md is generated from README.qmd. Please edit that file -->

```{r setup, include=TRUE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-",
  fig.retina = 3
)
```

::: {.content-visible when-format="markdown"}

---

[Cormac Monaghan](https://c-monaghan.github.io/)

---

:::

## Note on "crisp clam" project name

Because project titles change all the time we used [{codename}](http://svmiller.com/codename/) to generate an [Ubuntu-style](https://wiki.ubuntu.com/DevelopmentCodeNames)
internal-to-us project name that won’t change.

```{r code-name, eval=FALSE}
library(codename)

codename_message()
#> code name generated by {codename} v.0.5.0. R version 4.4.2 (2024-10-31 ucrt).

codename(seed = "dementia", type = "ubuntu")
#> [1] "crisp clam"
```

