---
title: "Procrastination and Dementia"
author: 
  - name: "Cormac Monaghan"
    url: "https://c-monaghan.github.io/"
    orcid: "https://orcid.org/0000-0001-9012-3060"
    affiliation:
      - "Hamilton Institute, Maynooth University, Ireland"
      - "Department of Psychology, Maynooth University, Ireland"
    email: cormacmonaghan@protonmail.com
    attributes:
      corresponding: true
  - name: "Rafael de Andrade Moral"
    url: "https://rafamoral.github.io/"
    orcid: "https://orcid.org/0000-0002-0875-3563"
    affiliation:
      - "Department of Mathematics and Statistics, Maynooth University, Ireland"
  - name: "Joanna McHugh Power"
    orcid: "https://orcid.org/0000-0002-7387-3107"
    affiliation: 
      - "Department of Psychology, Maynooth University, Ireland"
correspondence-prefix: "Correspondence concerning this article should be addressed to"
code-repo: "Access the code, data, and analysis at <https://github.com/C-Monaghan/crisp-clam>"
bibliography: references.bib
csl: csl/apa.csl
link-citations: true
---

::: {.content-visible when-format="html"}
# Introduction {.hide}
:::

Dementia is a syndrome characterized initially by the progressive and typically irreversible decline of cognitive function, leading to memory loss, impaired reasoning, and difficulties with activities of daily living [@Prince2013; @Sanz-Blasco2022]. It arises from various conditions, including Alzheimer's disease, vascular dementia, and Lewy body dementia [@Cao2020]. The global burden of dementia is substantial, with projections suggesting that the number of affected individuals will rise from 57.4 million in 2019 to 152.8 million by 2050 [@Nichols2022]. Given this projection, identifying and addressing modifiable risk factors is crucial to mitigate the growing prevalence difficulties with activities of daily living of dementia worldwide. In fact, targeting these factors could prevent up to 50% of dementia cases worldwide [@Livingston2024]. The *Lancet* Commission highlights 14 key modifiable risks, emphasizing that dementia risk can be reduced at any age. Nevertheless, age remains the strongest non-modifiable risk factor, accounting for the largest proportion of dementia cases.

Mild cognitive impairment (MCI) is a condition characterized by cognitive changes --- such as memory lapses or difficulty making decisions --- that exceed typical age-related decline [@Gauthier2006]. Prior studies suggest that 46% of people with MCI transition to a dementia state within three years and 80% within six years [@Cooper2015; @Shigemizu2020; @Tschanz2006]. However, progression is neither uniform nor inevitable. Heterogeneity in outcomes underscores the importance of distinguishing between two classes of predictors: causal risk factors (e.g. smoking, hypertension, or diabetes) which may accelerate dementia onset and are potential targets for intervention [@Livingston2024], and prodromal markers (e.g. memory loss, apathy, or struggles in daily living) that reflect early disease processes and may signal limited opportunities for prevention. While causal factors offer avenues for mitigating risk, prodromal features often emerge closer to irreversible pathological changes, highlighting the need for early detection and tailored interventions.

Apathy, defined as a significant loss of motivation, distinct from depression and cognitive impairment [@Fresnais2023; @Richard2012] is among the most prevalent neuropsychiatric symptoms in both MCI and dementia [@Donovan2014; @Fresnais2023; @Salem2023; @vanDalen2018]. Individuals with apathy exhibit reduced goal-directed behavior and a diminished desire to pursue rewards or pleasure [@Fresnais2023]. Importantly, apathy has been identified as a significant predictor for the transition from MCI to dementia [@Ruthirakuhan2019; @Salem2023; @vanDalen2018]. For instance, a meta-analysis by @vanDalen2018 found that apathy almost doubles the risk of transitioning to dementia. Additionally, levels of apathy measured using both the *"Neuropsychiatric Inventory Questionnaire\"* [@Kaufer2000] and *"Apathy Evaluation Scale\"* [@Marin1991] have shown to be correlated with higher levels of amyloid burden and neurofibrillary tangles in individuals with dementia, suggesting a potential connection to underlying neuropathology [@Donovan2014; @Marshall2013].

While apathy primarily reflects a lack of motivation, procrastination involves a delay in action despite an intention to complete such action [@Steel2007]. Although both behaviours indicate disruptions in goal-directed activity, they differ in their phenomenology: apathy is marked by diminished drive or emotional engagement, whereas procrastination typically involves intact intention but impaired follow-through. These differences suggest that procrastination may capture aspects of executive dysfunction and emotional regulation not fully accounted for by apathy alone.

Both behaviours have been linked with impaired executive function, particularly in goal-oriented behaviours, decision-making, and self-regulation [@Gustavson2015; @Kawagoe2017; @steel2010], domains which are frequently compromised in individuals with MCI and dementia [@Kirova2015; @Stopford2012]. While apathy has been well-established as a prodromal marker and risk factor for dementia progression [@Ruthirakuhan2019; @Salem2023; @vanDalen2018], emerging evidence also suggests a potential link between procrastination and early cognitive decline. For instance, @Friden2020 and @Zhang2019 highlight that chronic procrastination is associated with dysfunction in both the dorsolateral and ventromedial prefrontal cortices, regions of the brain known to not only show early degeneration in dementia [@Joseph2021], but also be linked to higher levels of apathy [@Fahed2021; @Zhang2019].

Furthermore, procrastination may exacerbate existing cognitive decline by reinforcing patterns of inaction and passivity. Individuals who chronically delay tasks may inadvertently engage in fewer cognitively stimulating activities, such as physical activity, problem-solving, decision-making, and goal-setting. Such activities are known to build cognitive resilience and reduce dementia risk [@Chowdhary2022; @Livingston2024]. By limiting engagement in such activities, procrastination may contribute to a self-reinforcing cycle of cognitive disengagement, potentially accelerating decline over time.

Given these behavioural and neuro-cognitive parallels with apathy, it is worth exploring whether chronic procrastination could serve as an early behavioural marker for cognitive impairment, or even a risk factor for dementia, especially in older adults. By examining procrastination alongside apathy, we may uncover a broader behavioural phenotype indicative of early neuropathological changes. Crucially, procrastination may identify individuals with motivational or executive dysfunction who do not yet meet the threshold for apathy, offering a potentially valuable and earlier behavioural marker for neurodegenerative risk.

Moreover, since age remains the strongest predictor of MCI and dementia, it is important to consider how behavioural predictors such as procrastination operate across the lifespan. Many established modifiable risk factors such as, hypertension, hearing loss, smoking, and social isolation, exert age-dependent effects, with certain factors carrying more weight at midlife than in late life [@livingston2020; @Livingston2024]. In light of this, we sought to explore whether procrastination also demonstrates an age-dependent risk profile. Understanding how procrastination interacts with age may help clarify its role in the aetiology of cognitive decline and identify windows of opportunity for targeted intervention.

Although current research on procrastination in relation to dementia is non-existent, this possible association warrants exploration. Identifying procrastination as a potential risk factor could expand the scope of early interventions aimed at preventing or slowing the progression of dementia. As such, the purpose of this study was to (a) assess group differences in procrastination levels across the normal cognition, MCI, and dementia groups, and b) test the hypotheses that higher levels of procrastination would be associated with an increased probability of transitioning from normal cognitive function or MCI to dementia.

# Method

## Data and study population

Analyses were conducted using a secondary data source; a multi-wave prospective cohort study called the Health and Retirement Study (HRS; [@Fisher2018], which tracks the health, economic, and social well-being of over $18,000$ American adults primarily aged $>50$. The HRS is managed by the Institute for Social Research at the University of Michigan, with data collected every two years. Initial data collection of a participant is conducted through a face-to-face interview, with follow-up biennial interviews conducted either by phone or face-to-face. The average re-interview response rate ranges from $68.8\%$ to $92.3\%$ [@HRS2017]. At the time of writing, fifteen years of HRS data are currently archived.

For this study, we focused on four waves of HRS data (from 2016 to 2022). Specifically our study sample consisted of respondents who participated in an experimental module assessing procrastination during the 2020 wave. These experimental modules, administered at the end of the core HRS interview, consist of concise questionnaires designed to explore new topics or supplement existing core survey data. Each respondent receives only one experimental module, with sample sizes for each module constituting approximately 10% of the core sample. As a result, while the core HRS sample includes approximately $18,000$ respondents, our initial sample of interest consisted of $1,368$ respondents. We excluded respondents with missing cognitive assessment data for any wave $(n = 419)$, those under 60 years of age $(n = 398)$, and those with complete missing values across the procrastination measure $(n = 2)$. This resulted in a final analytic sample of $549$ respondents.

## Measures

### Outcome: Cognitive Function and Cognitive Category

Cognitive function in the HRS is assessed using a series of tests adapted from the Telephone Interview for Cognitive Status (TICS; [@Brandt1988; @Fong2009]. These tests include an immediate and delayed $10$-noun free recall test, a serial seven subtraction test, and a backward count from $20$ test. Based on these assessments, @Crimmins2011 developed both a $27$-point cognitive scale and validated cut-off points to assess and classify cognitive status. Using these points, respondents who scored $12 - 27$ were classified as having normal cognition, $7 - 11$ as having MCI, and $0 - 6$ as having dementia.

### Predictor: Procrastination

Procrastination was measured using the Pure Procrastination Scale [@steel2010], which consists of 12 items rated on a Likert scale ranging from $1$ (strongly disagree) to $5$ (strongly agree). The total procrastination score ranges from $12$ to $60$, with higher scores indicating greater procrastination. The Pure Procrastination Scale conducted in 2020 (wave 3) had a Cronbach's $\alpha$ score of $0.92$ in this sample, indicating high internal consistency. An example of a question from the scale includes "I delay making decisions until it's too late".

### Confounders

To account for potential confounding, we controlled for variables withestablished associations with cognitive function and procrastination. These included measures of of age, sex, educational attainment, and depressive symptoms [@Abner2012; @Freedman2024; @Monaghan2024a; @Yu2013]. Educationalattainment was classified into three categories: no formal education, GED (General Educational Development)/high school diploma, and college/further education. Depressive symptoms were measured using an eight-item version of the Center for Epidemiological Studies Depression (CES-D) scale [@Briggs2018], with scores ranging from 0 to 8, demonstrating good internal consistency $(\alpha = 0.60)$.

## Data Analysis

All data analysis was carried out in R [@R2025]. Within the final dataset, missing data accounted for only 0.3%, all of which was contained within the educational attainment variable. To model transitions in cognitive states over time, we employed a first order discrete-time Markov model, a class of stochastic processes that satisfy the Markov property [@Zhang2010], which can be formally expressed as:

$$P(X_{t+1} = j \vert X_t = i, X_{t-1} = i_{t-1}, \dots X_0 = i_0) = P(X_{t+1} = j \vert X_t = i)$$

This property asserts that the probability of transitioning to a future state $X_{t+1}$ depends only on the current state $X_t$, and not on the full history of preceding states.

Unlike continuous-time models, discrete-time Markov models are not readily supported by a dedicated R package for deriving transition probabilities. Therefore, we implemented the model manually using multinomial logistic regression from the `nnet` package [@Venables2022]. This approach estimates the log-odds of transitioning to each non-reference state as a linear function of covariates, relative to a chosen reference category. For a system with $K$ cognitive states (with state $K$ as the reference), the model takes the form:

$$log \left( \frac{P(Y = j \vert x)}{P(Y = k \vert x)} \right) = \alpha + \beta_j^Tx \qquad \text{for } j = 1, \dots K-1$$

From these equations, the predicted transition probabilities for the non-reference states $j = 1, \dots, K - 1$ are derived as:

$$P(Y = j \vert x) = \frac{e^{\alpha_j + \beta_j^Tx}}{1 + \sum^{k - 1}_{k = 1} e^{\alpha_{k} + \beta_k^Tx}}$$

and for the reference state $K$ as:

$$P(Y = k \vert x) = \frac{1}{1 + \sum^{k - 1}_{k = 1} e^{\alpha_{k} + \beta_j^Tx }}$$

# Results

As mentioned, our initial sample of interest consisted of $1,368$ respondents. However, after excluding $819$ respondents our final analytic sample comprised $549$ respondents with the following age distribution: 60 - 70 $(n = 186)$, 71 - 80 $(n = 203)$, 81 - 90 $(n = 142)$, and 90+ $(n = 18)$. Descriptive statistics for the full sample, as well as stratified by cognitive status (normal cognition, MCI, and dementia), are presented in Table [\[table:1\]](#table:1){reference-type="ref" reference="table:1"}. Additionally, Table [1](#table:2){reference-type="ref" reference="table:2"} presents both the frequencies and estimated transition probabilities of cognitive status changes across waves. Specifically, it captures unconditional transitions between wave one and two (first transition), wave two and three (second transition), and wave three and four (third transition), yielding a total of 1,647 observed transitions over time.

*Note.* Descriptives for continuous and categorical variables are
represented using means $\pm$ standard\
\* deviations and percentages and frequencies respectively. NC = Normal
cognition; MCI = Mild\
\* cognitive impairment; GED = General Educational Development.
[]{#table:1 label="table:1"}

::: {#table:2}
  **2016**
  ---------- -------- -------- ----------
             NC       MCI      Dementia
  NC         (0.75)   (0.07)   (0.001)
  MCI        (0.09)   (0.06)   (0.01)
  Dementia   \(0\)    \(0\)    (0.02)
  **2018**
             NC       MCI      Dementia
  NC         (0.75)   (0.09)   \(0\)
  MCI        (0.07)   (0.03)   (0.02)
  Dementia   \(0\)    \(0\)    (0.03)
  **2020**
             NC       MCI      Dementia
  NC         (0.68)   (0.13)   (0.02)
  MCI        (0.05)   (0.05)   (0.01)
  Dementia   \(0\)    \(0\)    (0.05)

  : Frequencies (and transition probabilities) of cognitive status
  transitions from HRS waves.
:::

*Note.* NC = Normal cognition; MCI = Mild cognitive impairment
[]{#table:2 label="table:2"}

Initially, a Kruskal-Wallis test was conducted to examine differences in
procrastination scores (measured in 2020) across three cognitive status
groups after Levene's test indicated violation of homogeneity of
variance $(p = 0.039)$. The analysis revealed a statistically
significant effect of cognitive status, $(\chi^2(2) = 17.54, p < .001)$,
indicating that procrastination levels differed significantly between at
least two of the groups. Post-hoc analysis using a pairwise Wilcoxon
rank-sum test with a Benjamini-Hochberg correction showed that
participants with normal cognition $(M = 27.7, SD = 11.7)$ reported
significantly lower levels of procrastination than those with both MCI
$(M = 32.1; SD = 11.3; p = 0.004)$ and dementia
$(M = 36.2; SD = 14.8; p = 0.005)$. No significance difference was found
between those with MCI and dementia $(p = 0.334)$. Figure
[1](#fig:1){reference-type="ref" reference="fig:1"} displays the
distribution of procrastination scores across groups, with both boxplots
and dotplots showing median values and individual data points.
Significance bars indicate the pairwise differences described above.

<figure id="fig:1">
<p><embed src="Figures/fig_1.pdf" /> <span id="fig:1"
data-label="fig:1"></span></p>
<figcaption>Group differences in 2020 procrastination scores according
to cognitive status.</figcaption>
</figure>

## Markov analysis

Results from the discrete-time Markov analysis, showed that all covariates significantly influenced the likelihood of transitioning
between cognitive states (see Table [34](#table:3){reference-type="ref"
reference="table:3"}). Notably, procrastination interacted significantly
with age to affect two key transitions: increasing the likelihood of
transitioning from normal cognition to MCI
$(\text{OR} = 1.001; p < 0.001)$ and decreasing the likelihood of
reverting from MCI to normal cognition $(\text{OR} = 0.999; p < 0.001)$.

In addition women were significantly less likely than men to transition
from both normal cognition to dementia $(\text{OR} = 0.068; p < 0.001)$
and from MCI to dementia $(\text{OR} = 0.70; p < 0.001$). Educational
attainment was another strong predictor of cognitive transitions.
Individuals with a GED were less likely to transition from normal
cognition to either MCI $(\text{OR} = 0.49; p < 0.001)$ or dementia
$(\text{OR} = 0.29; p < 0.001)$ and from MCI to dementia
$(\text{OR} = 0.64; p < 0.001)$. They were also more likely to back
transition from MCI to normal cognition $(\text{OR} = 2.18; p < 0.001)$.

Furthermore, those with a college level education or higher demonstrated
a significantly reduced likelihood of transitioning from normal
cognition to either MCI $(\text{OR} = 0.32; p < 0.001)$ or dementia
$(\text{OR} = 0.07; p < 0.001)$ and from MCI to dementia
$(\text{OR} = 0.22; p < 0.001)$. They were also more likely to back
transition from MCI to normal cognition $(\text{OR} = 3.13; p < 0.001)$.

Finally, higher levels of depressive symptomatology were associated with
an increased likelihood of transitioning from normal cognition to both
MCI $(\text{OR} = 1.13; p = 0.002)$ and dementia
$(\text{OR} = 1.18; p = 0.046)$ and and a decreased likelihood of
transitioning from MCI back to normal cognition
$(\text{OR} = 0.89; p = 0.001)$.

|                |         Intercept         |           Gender          |            Age            |            GED            |
|----------------|:-------------------------:|:-------------------------:|:-------------------------:|:-------------------------:|
| NC - MCI       | 0.114***  (0.113 - 0.114) |   0.941  (0.690 - 1.284)  |  1.008**  (1.002 - 1.014) | 0.446***  (0.360 - 0.551) |
| NC - Dementia  | 0.009***  (0.009 - 0.009) | 0.669***  (0.662 - 0.687) |  1.023*** (1.010 - 1.035) | 0.295***  (0.289 - 0.302) |
| MCI - NC       | 9.008***  (8.986 - 9.030) |   1.061 (0.789 - 1.482)   |  0.992**  (0.986 - 0.997) |  2.46***  (1.829 - 2.759) |
| MCI - Dementia |  0.13***  (0.129 - 0.130) | 0.708***  (0.678 - 0.740) |   1.008  (0.995 - 1.021)  | 0.646***  (0.630 - 0.662) |
|                |     Further Education     |         Depression        |      Procrastination      |   Procrastination x Age   |
| NC - MCI       | 0.310***  (0.264 - 0.363) | 1.147***  (1.067 - 1.233) | 0.921***  (0.882 - 0.962) | 1.001***  (1.001 - 1.002) |
| NC - Dementia  | 0.068***  (0.068 - 0.068) |   1.150  (0.979 - 1.353)  |   0.981  (0.888 - 1.084)  |   1.000  (0.888 - 1.084)  |
| MCI - NC       | 3.240***  (2.789 - 3.762) | 0.872***  (0.811 - 0.937) | 1.085***  (1.039 - 1.134) | 0.999***  (0.998 - 0.999) |
| MCI - Dementia | 0.214***  (0.212 - 0.216) |   1.004  (0.852 - 1.184)  |   1.005  (0.952 - 1.168)  |   0.999  (0.998 - 1.001)  |

Finally, Figure┬á[2](#fig:2){reference-type="ref" reference="fig:2"}
presents the predicted transition probabilities across varying levels of
age and procrastination. These estimates illustrate how the interaction
between age and procrastination influences the likelihood of progressing
between cognitive states over time. Notably, while transition
probabilities remain relatively stable at very low levels of
procrastination, substantial shifts emerge as both age and
procrastination increase. In particular, older individuals with higher
procrastination scores show an elevated probability of cognitive decline
and a reduced likelihood of cognitive recovery, highlighting the
compounded risk posed by these two variables in later life.

<figure id="fig:2">
<p><embed src="Figures/fig_3.pdf" /> <span><em>Note.</em> Each curve
represents a different age profile, ranging from the minimum (62 years)
to the maximum (97 years) of the dataset. Specific ages of interest (70,
80, and 90) are highlighted.</span> <span id="fig:2"
data-label="fig:2"></span></p>
<figcaption>Predicted transition probabilities by procrastination and
age.</figcaption>
</figure>

# References